### ISSUE TITLE
contract deployment using eth_sendTransaction does not work

### ISSUE THREAD

**Issue by 4gn3s** [ethereum/pyethapp#100]
When you use [eth_sendTransaction](https://github.com/ethereum/pyethapp/blob/develop/pyethapp/rpc_client.py#L131) with "to" address set to empty, the address still gets encoded using data_encoder (in line [139](https://github.com/ethereum/pyethapp/blob/develop/pyethapp/rpc_client.py#L139)) and returns 0x instead of empty. Therefore the transaction is not considered a contract creation, but just a transaction between two accounts.

Example function call:
`res = self.eth_sendTransaction(sender=self.client.coinbase, data=binary, to='',                       gas=deploy_gas)`
creates a transaction from coinbase to 0x00. I was expecting a transaction from coinbase to empty.

The cause of the problem:
`data_encoder(b'') == '0x'` returns True
`data_encoder(b'') == ''` returns False

**Comment by RomanZacharia** [comment]
@4gn3s was the issue resolved? I see that the test_rpc_client.py passes well on the pyethapp/develop branch

**Comment by 4gn3s** [comment]
Yes, it seems to be solved. [This](https://github.com/ethereum/pyethapp/commit/49167b814ca84d2deb2edbc510e01cf7adfe45c2) commit fixes this.

**Comment by RomanZacharia** [comment]
@4gn3s thank you for the answer! Could you please close the issue here?

**Comment by 4gn3s** [comment]
Sure. thanks.
