### ISSUE TITLE
ipython version higher than 4.0.0 is broken

### ISSUE THREAD

**Issue by czepluch** [ethereum/pyethapp#104]
`Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "darwin" and platform_python_implementation == "CPython"`

https://gitter.im/ipython/ipython/archives/2015/11/29 <-- suggests to revert to 4.0.0

4.0.0 works fine. 

Suggested fix: set ipython==4.0.0 in requirements.txt

**Comment by czepluch** [comment]
Is fixed with https://github.com/ethereum/pyethapp/pull/106

**Comment by konradkonrad** [comment]
If I understand correctly, above error was specific to `4.0.0`, versions above that are working with the current code base. But, with ipython 5, a lot of breaking changes were introduced. Now ipython is pinned below `5.0.0` in `requirements.txt` (see 893e309cad9bf9907018576bc8bb88482e9f8efb).
