### ISSUE TITLE
Testnet sync timeout

### ISSUE THREAD

**Issue by ezdac** [ethereum/pyethapp#107]
## Checklist
- [x] installed `pyethapp` inside a virtualenv
## System/environment
- OS: Ubuntu 14.04.1
- python version: 2.7.11
- pyethapp version: 1.1.0
- installation method: pip
- pyethapp branch (if applicable): /
## Expected behaviour

```
pyethapp --profile morden run 
```

Should sync to the Morden-Testnet
## Observed behaviour

The default  [bootstrap enode](https://github.com/ethereum/pyethapp/blob/46f477c6cd5c23d9665accce53f73d6b5ad77c5e/pyethapp/profiles.py#L53-L55)
will time-out and won't allow syncing to the testnet. 
## Steps to reproduce

`pyethapp --profile morden run`
### 1)

Started geth client with `--testnet` and connected to the geth bootstrap-node locally
`pyethapp -b '<enodehash-from-geth>:127.0.0.1:30303' --profile morden run`
and set the listen ports on pyethapp accordingly.

In pyethapp's _config.yaml_ add:

```
discovery:
  listen_port: 30304
p2p:
  listen_port: 30304
```
### 2)

Change the Bootstrap-node, taken from the go-ethereum code.

```
pyethap -b enode://e4533109cc9bd7604e4ff6c095f7a1d807e15b38e9bfeb05d3b7c423ba86af0a9e89abbf40bd9dde4250fef114cd09270fa4e224cbeef8b7bf05a51e8260d6b8@94.242.229.4:40404 --profile morden run
```

**Comment by heikoheiko** [comment]
Can you repeat the test when not behind a nat (or behind a nat with opened ports like in boppwg).

**Comment by ezdac** [comment]
So the [go-testnet](https://github.com/ethereum/go-ethereum/blob/5490437942967638bcc6198035315f6811febaa8/eth/backend.go#L81) enode seems to work from the same network, but from a different machine (on which pyeth's `--testnet morden` isn't working as well). I will change the code as soon as it's evaluated on the other machine and a different network too. Right now I add it as workaround as well.
