### ISSUE TITLE
Could not find suitable distribution for devp2p 

### ISSUE THREAD

**Issue by yanik-ai** [ethereum/pyethapp#112]
## Checklist
- installed `pyethapp` inside a virtualenv
## System/environment
- OS: OS X EL Capital 
- python version: 2.7 
- pyethapp version: latest
- installation method (pip & pypi/git & setup.py): `env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" python setup.py install`
## Expected behaviour

```
Extracting ethereum-1.1.0-py2.7.egg to /Users/yanik/code/crypto_tickets/env2/lib/python2.7/site-packages
Adding ethereum 1.1.0 to easy-install.pth file
Installed .../env2/lib/python2.7/site-packages/ethereum-1.1.0-py2.7.egg
Searching for devp2p>=0.7.1
Reading https://pypi.python.org/simple/devp2p/
No local packages or download links found for devp2p>=0.7.1
error: Could not find suitable distribution for Requirement.parse('devp2p>=0.7.1')
```

I tried install devp2p manually with `pip install devp2p==0.7.1` but got next extension: 
https://gist.github.com/yanik5/0b46fedcd30437f47e17

**Comment by doyensyd** [comment]
Hi,
I had that problem a couple of hours ago but I just reinstalled pyethapp and pip finds pydevp2p 0.7.1
so perhaps the website has been updated.

When I encountered the problem what did was to download the pydevp2p 0.7.1 from the git repo and use pip to install from the local files.

git clone -b v0.7.1 https://github.com/ethereum/pydevp2p.git pydevp2p
pip install -e path_to_pydevp2p

You will see that if you do pip list you will find that pydevp2p is listed as well as the local directory

Cheers,
Aldo

**Comment by yanik-ai** [comment]
@doyensyd thx, but this wont help at all.

I tried re-install it and now the next error appears:
https://gist.github.com/yanik5/da2446d8dad55f067351

**Comment by doyensyd** [comment]
Hi Yanik,
Which version of python 2.7 do you have? 
Those errors that you listed in the file, I had when I was using python 2.7.5, they all disappeared when I used python 2.7.11 (or 2.7.9) .    

Once you install python 2.7.11  you will need to set the virtualenv with it
virtualenv --python=/path_to_python2.7.11_exec .venv
I hope that helps.
Cheers,
aldo

**Comment by yanik-ai** [comment]
@doyensyd, I was using `Python 2.7.10` from the beginning inside virtualenv as well . 

Probably should run it in ubuntu and avoid this headache.

**Comment by ulope** [comment]
@yanik5 From the log you posted it looks like you might not have all the necessary system dependencies installed. Please take a look [in the readme](https://github.com/ethereum/pyethapp#installation-on-os-x) and make sure you have all the packages installed.

A lot of the python core team also uses Macs so we want to make sure installation works smoothly.

**Comment by yanik-ai** [comment]
@ulope 

```
➜  ~ brew install automake pkg-config libffi gmp

Warning: automake-1.15 already installed
Warning: pkg-config-0.29.1 already installed
Warning: libffi-3.0.13 already installed
Warning: gmp-6.1.0 already installed
```

**Comment by yanik-ai** [comment]
I believe problem in `secp256k1` lib.

**Comment by ulope** [comment]
Please try again with PyEthApp 1.2.0. It should solve all of these problems. Please take note of the updated installation instructions in the readme.

**Comment by ulope** [comment]
We believe this issue has been fixed so I'm going to close it for now. If you still experience problems please open a new issue.
