### ISSUE TITLE
Cannot install "c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory"

### ISSUE THREAD

**Issue by jl2035** [ethereum/pyethapp#115]
## Checklist
- [0] trying to install using "pip install pyethapp"
## System/environment
- OS: ElementaryOS Freya (Ubuntu derivative)
- python version: 2.7.6
- pyethapp version: from the repo
- installation method (pip & pypi/git & setup.py): pip
- pyethapp branch (if applicable): master (I guess)
## Expected behaviour

One would expect that this thing would just install.
## Observed behaviour

Fatal error, compilation terminated, ending with:
"Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/secp256k1
Storing debug log for failure in /home/user/.pip/pip.log"

Here I pasted the terminal output: http://pastebin.com/C3mUssg2
and here is my installation log: http://pastebin.com/mTquesfW
## Steps to reproduce

I have no idea. One would probably need the same machine (HP Probook 6540b), same OS installation and then use the code from this repo.

**Comment by yanik-ai** [comment]
switch to `python 2.7.11`

**Comment by jl2035** [comment]
how do I do that within virutalenv?

**Comment by PXke** [comment]
Hello, I also see that in your terminal output you have a lot of : 
Python.h: No such file or directory
#include <Python.h>

Can you try please to install the development files ? With this command : 

`sudo apt-get install python-dev`

Then try again :) 

Have a nice day !

**Comment by jl2035** [comment]
After installing python-dev solved the problem..

I only get some warning about the missing c_secp256k1. But it somehow works.

> (pyethapp)user@laptop:~$ pyethapp run
> /usr/local/lib/python2.7/dist-packages/ethereum/specials.py:11: UserWarning: missing c_secp256k1 falling back to pybitcointools
>   warnings.warn('missing c_secp256k1 falling back to pybitcointools')
> /usr/local/lib/python2.7/dist-packages/ethereum/transactions.py:18: UserWarning: missing c_secp256k1 falling back to pybitcointools
>   warnings.warn('missing c_secp256k1 falling back to pybitcointools')

**Comment by yanik-ai** [comment]
@jl2035 yeah, same warning here 
this package not ideal

**Comment by ulope** [comment]
Please try again with PyEthApp 1.2.0 (released today). We've switched to a different package for secp256k1 support.

**Comment by ulope** [comment]
We believe this issue has been fixed. If you still experience problems please open a new issue.

**Comment by skishorekanna** [comment]
apt-get install python-dev worked.
Thanks a lot !!!

**Comment by ficolo** [comment]
A little note for Python 3 users, you should install python3-dev to solve the issue:

apt-get install python3-dev
