### ISSUE TITLE
JSONRPCClient listens only on localhost

### ISSUE THREAD

**Issue by 4gn3s** [ethereum/pyethapp#117]
JSONRPCClient should allow to define both the host address and the port of the Ethereum client. For now, JSONRPCClient always assumes the address is localhost. This improvement is useful e.g. when running the app and Ethereum client in separate docker containers. For now, the ugly workaround is:

`self.client = JSONRPCClient(port=ETH_CLIENT_PORT)`
`self.client.transport = HttpPostClientTransport('http://{}:{}'.format(ETH_CLIENT_ADDRESS, ETH_CLIENT_PORT))`

I think it would be better to be able to just do:
`self.client = JSONRPCClient(host=ETH_CLIENT_ADDRESS, port=ETH_CLIENT_PORT)`

**Comment by anton44eg** [comment]
In my project I rewrite **init**
New signature 
`def __init__(self, url='http://127.0.0.1:8545', print_communication=True, privkey=None, sender=None)`

But it will brake backward compatability
