### ISSUE TITLE
RPCClient https support

### ISSUE THREAD

**Issue by utzig** [ethereum/pyethapp#163]
When creating a new eth RPC connection, the `JSONRPCClient` receives a `host` and `port` from which a new `http` connection `URL` is created here:

https://github.com/ethereum/pyethapp/blob/develop/pyethapp/rpc_client.py#L121

This works with most eth clients (eg `geth`) but may be a limitation in other cases. For example, using `https://morden.infura.io` as backend does not work (because `http` is not supported).

**Comment by konradkonrad** [comment]
will be resolved in upcoming release (see #166)
