### ISSUE TITLE
"Failed building wheel for secp256k1" upon installation

### ISSUE THREAD

**Issue by deerdear** [ethereum/pyethapp#172]
## Checklist
- [x] installed `pyethapp` inside a virtualenv
## System/environment
- OS: OS X 10.11.6
- python version: 2.7
- pyethapp version: FIXME
- installation method (pip & pypi/git & setup.py): git
- pyethapp branch (if applicable): FIXME
## Expected behaviour

$ pyethapp
Usage: pyethapp [OPTIONS] COMMAND [ARGS]...

  Welcome to ethapp version:pyethapp/v0.9.18/linux2/py2.7.9

Options:
## Observed behaviour

I can't install pyethapp. It's failing at the secp256k1. 

This is the output I get when I try to install it: 

---

  Failed building wheel for secp256k1
[...]
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/qw/cwkm1m4s41z0l1trrv74s2c00000gn/T/pip-build-KxLQvu/secp256k1/build/temp.macosx-10.11-x86_64-2.7':
    configure: error: C compiler cannot create executables
    See`config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qw/cwkm1m4s41z0l1trrv74s2c00000gn/T/pip-build-KxLQvu/secp256k1/setup.py", line 274, in <module>
        "Topic :: Security :: Cryptography"
  [...]

```
----------------------------------------
```

Command "/Users/deerdear/Documents/Ethereum/pyethapp/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/qw/cwkm1m4s41z0l1trrv74s2c00000gn/T/pip-build-KxLQvu/secp256k1/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/qw/cwkm1m4s41z0l1trrv74s2c00000gn/T/pip-qX1P2u-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/deerdear/Documents/Ethereum/pyethapp/bin/../include/site/python2.7/secp256k1" failed with error code 1 in /private/var/folders/qw/cwkm1m4s41z0l1trrv74s2c00000gn/T/pip-build-KxLQvu/secp256k1/`
## Steps to reproduce

Followed the guide: https://github.com/ethereum/pyethapp/wiki/Getting-Started

**Comment by ulope** [comment]
The important part is this: 

> `configure: error: C compiler cannot create executables See config.log`

This is most likely caused by an outdated installation of Xcode. Please see https://github.com/ethereum/pyethapp/blob/develop/docs/installation_os_x.rst for detailed instructions on how to set up your Mac.

**Comment by deerdear** [comment]
Thanks! I suspected it might be that. I updated and reinstalled command line tools and now it worked!

**Comment by deerdear** [comment]
Thanks it worked!
