### ISSUE TITLE
AssertionError: sorry, but this version only supports 100 named groups

### ISSUE THREAD

**Issue by shikhi7** [ethereum/pyethapp#173]
## Checklist
- [yes] installed `pyethapp` inside a virtualenv
## System/environment
- OS: ubuntu 16.04
- python version: 2.7
- pyethapp version: not sure
- installation method (pip & pypi/git & setup.py): installation from github
- pyethapp branch (if applicable): FIXME

I am following the instructions from here : https://github.com/ethereum/pyethapp/wiki/Getting-Started
to install pyethapp from Github. However when I tried to run pyethapp, it shows this error message:

"sorry, but this version only supports 100 named groups"
AssertionError: sorry, but this version only supports 100 named groups

I know this has something to deal particularly with my machine and regex but I am unable to solve it. Please help.

[error.pdf](https://github.com/ethereum/pyethapp/files/505971/error.pdf)
## Steps to reproduce

FIXME

**Comment by konradkonrad** [comment]
Hey! This finally also hit on the travis-ci builds. It seems to be due to these issues:

https://github.com/eliben/pycparser/issues/147
https://github.com/eliben/pycparser/issues/151

As a workaround I suggest, you manually install `pycparser` first and then follow with the installation of pyethapp:

```
pip install pycparser==2.14  # that seems to work now
pip install pyethapp
```

**Comment by konradkonrad** [comment]
Also, just while I wrote you, the issue seems to have been addressed: https://github.com/eliben/pycparser/issues/151#issuecomment-254551279
So you should be able to just retry installing in a fresh virtualenv (without any workarounds).
