### ISSUE TITLE
josnrpc: implement cross-origin resource sharing

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#18]
Equivalent to geth:

`geth --rpccorsdomain http://etherex.github.io`

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by jnnk** [comment]
Done (see e5fd0d0067b1e294087dac8fc248e37be95be20c)

``-c jsonrpc.corsdomain=http://groupgnosis.com``

**Comment by heikoheiko** [comment]
cool!
