### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by lisanka93** [ethereum/pyethapp#186]
i cannot follow the installation instructions
it gives me the following error when i run develop

Installed /home/user/pyethapp
Processing dependencies for pyethapp==1.5.0
error: rlp 0.4.7 is installed but rlp<=0.4.6,>=0.4.4 is required by set(['devp2p'])

**Comment by gsalgado** [comment]
Here's the devp2p commit where they pinned rlp to <=0.4.6: https://github.com/ethereum/pydevp2p/commit/1b4647f500bdb495c77518e55b94b97a1125739c

Maybe that needs to be done in pyethapp as well, until ethereum/pyethereum#412 is fixed?

**Comment by gsalgado** [comment]
Maybe just swapping the order of the devp2p and rlp lines in requirements.txt would fix this, as rlp<=0.4.6 would be installed as a requirement of devp2p and when pip gets to the rlp>=0.4.4 line it will already be satisfied and won't end up installing 0.4.7 (latest)

**Comment by powerLambda** [comment]
+1 have same error. it seems that swapping the order does not work. @gsalgado

**Comment by byrnenick** [comment]
I couldnt reproduce this error. But, after installing a new system and trying to bring this back to life, pip install devp2p was failing. It was a simple solution as I was just missing python-dev, perhaps try sudo apt-get install python-dev and try again (assuming you're on ubuntu/debian)?

**Comment by krutwl9** [comment]
Hi, did anyone figure this out? I had the same issue while building docker for hydrachain.

**Comment by ravl1084** [comment]
Having this issue as well.

**Comment by krutwl9** [comment]
Remove the following code from hydrachain/docker/dev/hydrachain/node: 
line 26
RUN python setup.py install

hydrachain/makefile line 60
release: clean
    python setup.py sdist upload
    python setup.py bdist_wheel upload

dist: clean
    python setup.py sdist
    python setup.py bdist_wheel
    ls -l dist

install: clean
    python setup.py install

**Comment by joeblankenship1** [comment]
This is great; thanks very much to everyone involved!
