### ISSUE TITLE
Cannot import name casper_utils! :-(

### ISSUE THREAD

**Issue by 5chdn** [ethereum/pyethapp#207]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Ubuntu 16.4 LTS
- python version: 2.7.12
- pyethapp version: 1.5.0-git-7d5ca47
- installation method (pip & pypi/git & setup.py): git + pip
- pyethapp branch (if applicable): develop, latest

## Expected behaviour

- run fine :)

## Observed behaviour

    (.venv) ~/src/pyethapp$ pyethapp
    Traceback (most recent call last):
      File "/home/user/src/pyethapp/.venv/bin/pyethapp", line 11, in <module>
        load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
      File "/home/user/src/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/user/src/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/home/user/src/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/user/src/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/user/src/pyethapp/pyethapp/app.py", line 19, in <module>
        from ethereum import casper_utils
    ImportError: cannot import name casper_utils

## Steps to reproduce

On a clean Ubuntu 16.4 LTS machine:

    ~$ sudo apt update
    ~$ sudo apt dist-upgrade
    ~$ sudo apt install python python-pip git virtualenv libssl-dev
    ~$ mkdir src
    ~$ cd src
    ~/src$ git clone https://github.com/ethereum/pyethapp
    ~/src$ cd pyethapp
    ~/src/pyethapp$ virtualenv .venv
    ~/src/pyethapp$ source .venv/bin/activate
    (.venv) ~/src/pyethapp/$ pip install --editable .
    (.venv) ~/src/pyethapp/$ pyethapp

(On a side-note, libssl-dev is missing in your [prerequisites](https://github.com/ethereum/pyethapp/wiki/Getting-Started#prerequisites).)

**Comment by LiyanJin** [comment]
I have met the same problem.  I downloaded the pyethapp on branch of develop and tried to run it on ether public chain or test chain. However it said "ImportError: cannot import name casper_utils" . Any idea?
BTW, I also downloaded pyethereum on branch of develop.

**Comment by shiqinfeng1** [comment]
I met too ！

**Comment by janx** [comment]
Make sure you're using develop branch of pyethereum. An easy way to do this is using [USE_PYETHEREUM_DEVELOP](https://github.com/ethereum/pyethapp/blob/develop/setup.py#L50) flag.

**Comment by LiyanJin** [comment]
Thx Janx. Your suggestion really works for me. 
I reinstalled pyethereum by following steps as below:
$ git clone https://github.com/ethereum/pyethereum/
$ cd pyethereum
$ git checkout develop
$ pip install -r dev_requirements.txt
$ python setup.py develop
It will install pyethereum (branch develop) and pyethapp (branch develop) can work  successfully with it.
However, when the pyethapp is trying to connect to my private chain which is setup by Geth client（version 1.6.1), it shows the below information repeatedly.
INFO:p2p.peer  received hello client_version~~~~~
Furthermore, It can't sync with the Geth client (version 1.6.1).

**Comment by janx** [comment]
@LiyanJin thanks for your feedback!

pyethapp may not work with private chain as it requires peer to pass DAO fork block challenge: https://github.com/ethereum/pyethapp/blob/develop/pyethapp/eth_service.py#L434
