### ISSUE TITLE
ImportError: cannot import name blocks

### ISSUE THREAD

**Issue by Marto32** [ethereum/pyethapp#241]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Linux Debian 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 GNU/Linux
- python version: 2.7.13
- pyethapp version: 1.5
- installation method (pip & pypi/git & setup.py): pip
- pyethapp branch (if applicable): n/a

## Expected behaviour
Console should start after running `pyethapp -d /data run --console`

## Observed behaviour
```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```

## Steps to reproduce
 1. Build the docker image with the `Dockerfile` pasted below: `docker build -t pyethapp:devtest .`
 2. run `docker run -it --entrypoint /bin/bash pyethapp:devtest`
 3. once in the shell, run `pyethapp -d /data run --console`

Initially, I was getting the error noted in #199. The suggested fix there was to downgrade `pyelliptic` via `pip install pyelliptic==1.5.7`. This seems to have worked for some people, but others are receiving the `ImportError` noted in the **Observed behaviour** section above.

Per [this point in the issue conversation](https://github.com/ethereum/pyethapp/issues/199#issuecomment-312154907) I attempted to add the following to a customized `requirements.txt` file:

```
Cython==0.25.2
pyelliptic==1.5.7
https://github.com/ethereum/pyethereum/archive/0ae64823d1bccba9c8148adb462060cb83c08f06.zip
https://github.com/ethereum/pydevp2p/archive/cc68f6d69fa88ffaac6f8483392c37eb9f19d712.zip
https://github.com/ethereum/pyethapp/archive/409331e88a397ce5276c430aff4a8866d413e45d.zip
pyethash==0.1.27
```

`Dockerfile` (which builds successfully):

```
FROM python:2

RUN apt-get update
RUN apt-get install -y \
  git-core \
  build-essential \
  automake \
  pkg-config \
  libtool \
  libffi-dev \
  libgmp-dev \
  python-dev \
  python-pip

RUN pip install pyethapp

# Fix debian's ridiculous gevent-breaking constant removal
# (e.g. https://github.com/hypothesis/h/issues/1704#issuecomment-63893295):
RUN sed -i 's/PROTOCOL_SSLv3/PROTOCOL_SSLv23/g' /usr/local/lib/python2.7/site-packages/gevent/ssl.py

# Update requirements as noted in this conversation:
# https://github.com/ethereum/pyethapp/issues/199#issuecomment-304724903
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN mkdir /data

EXPOSE 8888
EXPOSE 4000
EXPOSE 30303
EXPOSE 30303/udp

VOLUME /data
```

My `pip freeze` output is as follows:

```
backports.shutil-get-terminal-size==1.0.0
bitcoin==1.1.42
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
CodernityDB==0.5.0
coverage==4.4.1
Cython==0.25.2
decorator==4.0.11
devp2p==0.9.2
docutils==0.13.1
enum34==1.1.6
ethereum==1.6.1
gevent==1.1.0
gipc==0.4.0
greenlet==0.4.12
idna==2.5
ipaddress==1.0.18
ipython==4.2.1
ipython-genutils==0.2.0
leveldb==0.194
lmdb==0.92
miniupnpc==1.9
pathlib2==2.3.0
pbkdf2==1.3
pexpect==4.2.1
pickleshare==0.7.4
pluggy==0.4.0
ptyprocess==0.5.2
py==1.4.34
pycparser==2.17
pycryptodome==3.4.6
pyelliptic==1.5.7
pyethapp==1.5.0
pyethash==0.1.27
pysha3==1.0.2
PyYAML==3.12
repoze.lru==0.6
requests==2.18.1
rlp==0.5.1
scandir==1.5
scrypt==0.8.0
secp256k1==0.13.2
simplegeneric==0.8.1
six==1.10.0
statistics==1.0.3.5
tinyrpc==0.5
tox==2.7.0
traitlets==4.3.2
urllib3==1.21.1
virtualenv==15.1.0
Werkzeug==0.12.2
```

**Comment by AndreMiras** [comment]
Nice report!
Your stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```
Shows it's not running in a virtualenv: `/usr/local/lib/python2.7/site-packages/`
So remove the pyethapp install and everything you installed not in the venv, it might be conflicting with your venv.

**Comment by Marto32** [comment]
Thanks! Do I still need a virtual env even if I'm building a docker container just for this install?

**Comment by AndreMiras** [comment]
I would still recommend so it doesn't conflict with system modules.

**Comment by Marto32** [comment]
Ok thanks I'll give that a try

**Comment by Marto32** [comment]
@AndreMiras so I have recreated the container with all requirements and pyethapp in a virtual environment. I receive the same error - the Traceback leads to the version in my venv now:
```
Traceback (most recent call last):
  File "/.virtualenvs/ethereum27/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/.virtualenvs/ethereum27/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```

**Comment by Marto32** [comment]
So I solved the build issue with a new dockerfile but am receiving some console trouble now. Closing this and using the initial dockerfile ticket #230

**Comment by snario** [comment]
@Marto32 what do you mean "solved with a new dockerfile"? How did you get around it?

**Comment by Gary-H9** [comment]
To echo @snario, can you update us @Marto32? I am receiving the same error as you (not running this in a venv).

```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```

**Comment by Marto32** [comment]
@snario @AndreMiras @Gary445 

I ended up building a boilerplate dev environment for myself (available [here](https://github.com/Marto32/ethbase)). I finally got everything to work using [this Dockerfile](https://github.com/Marto32/ethbase/blob/master/Dockerfile). There are two ways you can launch that environment after building the container - check out the README for directions. Or you can just use the Dockerfile to build your own.

It took me hours upon hours to finally get this all working so if you encounter problems please LMK. That said, the constant changes applied to `pyethapp` and its underlying dependencies make it difficult to keep a stable dev environment up and running. Hopefully that changes!

**Comment by kant111** [comment]
I am getting the same error and I am not using docker. I am using mac and all my installation was successful (no errors) the moment I type in pyethapp. I get this

```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ethereum 

Looks like there is no `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ethereum/blocks.py` but there is `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ethereum/block.py `

**Comment by kant111** [comment]
Looks like there is no blocks.py but there is block.py

**Comment by hwwhww** [comment]
@kant111 
Hi, you need to use pyethapp `1.5.1a0`

Check if you can see `1.5.1a0`
```
root@25ae12fcf2a3:/pyeth/pyethapp# pip search pyethapp
captureth (0.0.6)   - Capture msgs from pyethapp
pyethapp (1.5.1a0)  - Python Ethereum Client
  INSTALLED: 1.5.0
  LATEST:    1.5.1a0
```

Install specific version
```
pip install pyethapp==1.5.1a0
```

**Comment by kant111** [comment]
@hwwhww Thanks I passed through that but looks like I still cannot access some functions  like `get_transactions()` or `get_balance()`

`In [4]: eth.latest.get_transactions()`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-f91c2e1449dd> in <module>()
----> 1 eth.latest.get_transactions()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ethereum/block.pyc in __getattribute__(self, name)
    179             return rlp.Serializable.__getattribute__(self, name)
    180         except AttributeError:
--> 181             return getattr(self.header, name)
    182 
    183     @property

AttributeError: 'BlockHeader' object has no attribute 'get_transactions'
````
` eth.latest.get_balance(eth.coinbase)`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a62287bc34a6> in <module>()
----> 1 eth.latest.get_balance(eth.coinbase)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ethereum/block.pyc in __getattribute__(self, name)
    179             return rlp.Serializable.__getattribute__(self, name)
    180         except AttributeError:
--> 181             return getattr(self.header, name)
    182 
    183     @property

AttributeError: 'BlockHeader' object has no attribute 'get_balance'

```

**Comment by AndreMiras** [comment]
@kant111 I didn't verify for this one particularly, but I would suggest in general is to run unit test and compare the outcome with https://travis-ci.org/ethereum/pyethapp/builds
It could also be that this part is not covered, but is is also pretty straightforward to verify.
Happy digging! ;)

**Comment by kylelol** [comment]
@kant111 after setting up & activating my virtualenv (steps 6 & 7 of [this](https://github.com/ethereum/pyethapp/blob/develop/docs/installation_os_x.rst)), I ran `pip install pyethapp==1.5.1a0` and it gets rid of the import error
