### ISSUE TITLE
inconsistent version of rlp in development version installation

### ISSUE THREAD

**Issue by matsulib** [ethereum/pyethapp#253]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Ubuntu 16.04
- python version: Python 2.7.12
- pyethapp version: GITHUB clone
- installation method (pip & pypi/git & setup.py): USE_PYETHEREUM_DEVELOP=1 python setup.py develop

## Expected behaviour
installation success

## Observed behaviour

```bash
(venv) $ USE_PYETHEREUM_DEVELOP=1 python setup.py develop

error: rlp 0.6.0 is installed but rlp<0.6.0,>=0.5.1 is required by set(['devp2p'])
```

It seems that rlp versions are inconsistent between pyethapp and devp2p.

**Comment by pglezen** [comment]
I observe the same behavior using this procedure.

1. Created a new conda environment with `conda create -n eth python=2.7`.
2. Activated new environment.
3. Cloned pyethapp into a directory of the same name.
4. Changed to `pyethapp`.
5. Ran `pip install --editable .`.

I received lots of encouraging messages during the set-up.  But upon running `pyethapp` I received the following at the bottom of the stack trace.

```
File "/Users/*****/anaconda/envs/eth/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 859, in resolve
pkg_resources.ContextualVersionConflict: 
(rlp 0.6.0 (/Users/*****/anaconda/envs/eth/lib/python2.7/site-packages), 
Requirement.parse('rlp<0.6.0,>=0.5.1'), set(['devp2p']))
```

* OS: `Mac OS 10.12.6`
* pip: `9.0.1`
