### ISSUE TITLE
export accounts to use in geth

### ISSUE THREAD

**Issue by shayanb** [ethereum/pyethapp#28]
This might be a really newbie question but I have problems importing the acconts generated by pyethapp to geth. Is there a procedure for that?

**Comment by shayanb** [comment]
I copied the keystores from ~/Library/Application Support/pyethapp to ~/Library/Ethereum/keystore but it can't see the files, I guess it indexes the addresses somewhere else too, and the only difference between geth generated address and pyethapp ones are the filenames (geth adds timestamp at the beginning of the filename)

**Comment by shayanb** [comment]
somehow after generating a new address with geth, it could identify the other addresses.

```
cp keystore/* ~/Library/Ethereum/keystore/
```

**Comment by shayanb** [comment]
but still can't unlock the imported addresses:

```
could not unlock signer account
    at InvalidResponse (<anonymous>:-60926:-175)
    at send (<anonymous>:-124886:-175)
    at sendTransaction (<anonymous>:-113803:-175)
    at <anonymous>:1:1
```

**Comment by jnnk** [comment]
You have to rename the file to follow geth's naming convention (``UTC--<timestamp>--<address>``). ``UTC--0--<address>`` should work.

If this does not help, could you check the password in geth's console with ``personal.unlockAccount``? This would print a more helpful error message.

**Comment by shayanb** [comment]
changing the name worked. thanks
