### ISSUE TITLE
Pyethapp   install   failed.

### ISSUE THREAD

**Issue by djalmabright** [ethereum/pyethapp#290]
+ pip install pyethapp
Collecting pyethapp
  Downloading pyethapp-1.5.0-py2.py3-none-any.whl (335kB)
Collecting devp2p>=0.8.0 (from pyethapp)
  Downloading devp2p-0.9.3.tar.gz (74kB)
Collecting pyyaml (from pyethapp)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting click (from pyethapp)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting leveldb (from pyethapp)
  Downloading leveldb-0.194.tar.gz (228kB)
Collecting statistics (from pyethapp)
  Downloading statistics-1.0.3.5.tar.gz
Collecting rlp>=0.4.4 (from pyethapp)
  Downloading rlp-0.6.0.tar.gz
Collecting scrypt (from pyethapp)
  Downloading scrypt-0.8.6.tar.gz (52kB)
Collecting werkzeug (from pyethapp)
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
Collecting ipython<5.0.0,>=3.0.0 (from pyethapp)
  Downloading ipython-4.2.1-py3-none-any.whl (737kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.6/site-packages (from pyethapp)
Collecting ethereum>=1.5.1 (from pyethapp)
  Downloading ethereum-2.3.0.tar.gz (153kB)
Collecting lmdb (from pyethapp)
  Downloading lmdb-0.93.tar.gz (870kB)
Collecting requests (from pyethapp)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting gipc==0.4.0 (from pyethapp)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bn2auk2u/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bn2auk2u/gipc/

**Comment by RobiGit2017** [comment]
yes...I have same problem.
so...How to install pyethapp by Anaconda ??

I got the problem in the Python 3.6 +Win7 x64 or Python 2.7 +Win7 x64 or Python 3.6 +ubuntu 16 x64 or Python 2.7 +ubuntu 16 x64

**Comment by maxhallhatesm3** [comment]
@djalmabright @RobiGit2017 

Was there a fix for this?

I am on Ubuntu 18.xx and have tried with Python 2.7 ( iaw git repo req's ) as well as Python 3 ( iaw ERR 'eth-hash requires Python '>=3.5, <4' but the running Python is 2.7.15'

Tried:

pip[3] install gipc

still getting: 

Command "python setup.py egg_info" failed with error 
code 1 in /tmp/pip-build-********/gipc/
