### ISSUE TITLE
missing jsonrpc methods

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#35]
[ ] eth_getTransactionReceipt (most important)
[ ] eth_sign
[ ] eth_protocolVersion
[ ] eth_estimateGas
[ ] eth_newPendingTransactionFilter
[ ] eth_getLogs (coordinate with new slogging)

**Comment by heikoheiko** [comment]
@jnnk can you update or close this issue?

**Comment by jnnk** [comment]
[x] eth_getTransactionReceipt (most important)
[ ] eth_sign
[x] eth_protocolVersion
[x] eth_estimateGas
[x] eth_newPendingTransactionFilter
[x] eth_getLogs (coordinate with new slogging)
