### ISSUE TITLE
Convert all occurences of "print" to a log message.

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#38]
pyethereum
pyethapp
pydevp2p
pyrlp

might be affected.

**Comment by konradkonrad** [comment]
Also reconsider all writes to `sys.stderr`.

**Comment by heikoheiko** [comment]
during development colored debug output can be very helpful, therefore this hack exits:
https://github.com/ethereum/pyethereum/blob/develop/ethereum/utils.py#L405  

proposal:
add a new log level 'DEV' which when formatted adds escape codes for colored output in the terminal.
i.e. `log.DEV('something')` should output `something` in red color independent of the active loglevel.

obviously log.DEV should be removed or rewritten to a different level before released.

**Comment by inzem77** [comment]
which is debug level for change "print" message ? I think INFO level.

**Comment by inzem77** [comment]
Do i change the "print" into test_* files ?
For example test_pruning_trie.py, print(db.kv)
