### ISSUE TITLE
ethash requirements during install

### ISSUE THREAD

**Issue by ethers** [ethereum/pyethapp#41]
I was unable to sync the chain until cloning https://github.com/ethereum/ethash and then installing ethash with `python setup.py install`.  Should these steps be mentioned in the readme?

**Comment by heikoheiko** [comment]
how did you install the client? i have no such problem when installing the client with 
`pip install pyethapp` in a clean virtualenv.

**Comment by ethers** [comment]
I was following the readme:
git clone https://github.com/ethereum/pyethapp
cd pyethapp
python setup.py install
