### ISSUE TITLE
Pyethapp install failed

### ISSUE THREAD

**Issue by jmiehau** [ethereum/pyethapp#43]
On Ubuntu 15, I am trying to install the python ethereum client.

I got this error:
`compilation terminated.`
`error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

full logs:
https://gist.github.com/jmiehau/8a945c3c652a137d1430

Already I tried to search for an answer:
http://stackoverflow.com/questions/26053982/error-setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-wit
http://stackoverflow.com/questions/29778715/pip-install-reportlab-error-command-x86-64-linux-gnu-gcc-failed-with-exit-sta

**Comment by heikoheiko** [comment]
could you resolve the issue? otherwise can you please bring it up here:
https://bitbucket.org/mhallin/py-scrypt/src
