### ISSUE TITLE
Gracefully handle wrong command line options

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#46]
Currently wrong parametrization is mostly catched by asserts, which raise an AssertionError instead of a helpful error message.

Task:
 - Identify possibilities of wrong parametrization
 - Identify the asserts raised
 - Change these asserts to raised Exceptions with identifiable names
 - Catch these exceptions on startup and report a meaningful error message

**Comment by inzem77** [comment]
1. We start only pyethapp as app. Must i change "assert" to "raise" only in app.py file ?
2. We have many different function in pyethapp, pyethereum, pydevp2p, pyrlp and many function have parameters. Must i change "assert" to "raise" in these functions ?
