### ISSUE TITLE
New blocks + genesis handling broke jsonrpc tests

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#50]
@jnnk
https://github.com/ethereum/pyethapp/commit/b50e9da309dd2f4f6bdcc0a0b0e239d1b4202baf

i didn't take a closer look, but it seems that there are no funds to send txs (maybe need to add some alloc to the genesis). event tests stall if the tx fails.

**Comment by jnnk** [comment]
Fixed in 7e4d8caa0ef9ce6a71d27484241b77561fe4ed12
