### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyethapp#51]
- creating and setting custom genesis files

**Comment by panpilkarz** [comment]
Is it correct and enough?

https://github.com/ms83/pyethereum/wiki/Genesis-files

**Comment by panpilkarz** [comment]
New version: https://github.com/ms83/pyethereum/wiki/Genesis-files

Regarding `test_privkeys` in hydra: I think there is nothing to do in that issue.

**Comment by heikoheiko** [comment]
The `-C -d` example is not good, as it will load the same config file, if at all. i think -C should point to a file, not a dir. 

the option to load a genesis from a non config wile should be documented. 

documentation should go to pyethapp wiki. 
`test_privkeys` needs documetnation. 

 also, there should be tests (see click.CLIRunner). these could be linked in the documentation as an example.

I can't easily verify the documentation, as there are no tests.

**Comment by panpilkarz** [comment]
> The -C -d example is not good

Double checked and `-C` and `-d` are fine:

```
$ python pyethapp/app.py -C ~/.config/pyethapp2/ -d ~/.config/pyethapp2/ run 2>&1 | egrep '(loading config path|using data in path)' 
INFO:app    using data in path=/home/marcin/.config/pyethapp2/
INFO:config loading config path=/home/marcin/.config/pyethapp2/
```

> the option to load a genesis from a non config wile should be documented.

It is indeed documented. Pls take a look paragraph 2. Option `-c`

> documentation should go to pyethapp wiki. 

That is just a draft. Once accepted will go to pyethapp of course.

> test_privkeys needs documetnation.

`test_privkey` is never referenced in `pyethapp`:

```
(eth)[fix-load-genesis]~/Ethereum/pyethapp$ grep -r test_privkey .
(eth)[fix-load-genesis]~/Ethereum/pyethapp$ 
```

Confused. Did you mean Hydrachain?

> CLIRunner

Will take a look that.

**Comment by panpilkarz** [comment]
3rd approach to load custom config file: https://github.com/ms83/pyethereum/wiki/Genesis-files

**Comment by panpilkarz** [comment]
New version: https://github.com/ms83/pyethapp/wiki/Custom-genesis

Yes `-C` was incorrect. IMO app should exit if `-C` is set but to invalid value. Currently app silently loads default config if `-C` was set to incorrect value.

```
$ pyethapp -C non-existing.yaml run
$ pyethapp -C WTF run
```

I added warning for that case in the code: https://github.com/ethereum/pyethapp/pull/79/files#diff-bc10ed257cd89eeec14fb171ff8faaf0R93

**Comment by heikoheiko** [comment]
It should exit if the file is not available. Actually it should exit on all invalid commandline options. Users probably won't read the logs.

**Comment by heikoheiko** [comment]
tests are good, but it still lacks a test for a genesis.json file (i.e. only the alloc) on the cli. 
e.g. `-c eth.genesis=myalloc.json`

**Comment by panpilkarz** [comment]
Now it is covered: https://github.com/ms83/pyethapp/wiki/Custom-genesis
Test cases delivered: https://github.com/ms83/pyethapp/commit/49224c26d8fce11a63cfcd648d2e2062ea18ccd8

**Comment by panpilkarz** [comment]
Exit app if config is not available and test coverage.

https://github.com/ms83/pyethapp/commit/c1982d9d240f2e5e0b7f2efe6110a0cc5f9520d3

**Comment by panpilkarz** [comment]
Doc moved to final destination: https://github.com/ethereum/pyethapp/wiki/Custom-genesis

Checked that app exits on all invalid commandline options.

Issue can be closed.
