### ISSUE TITLE
specifiable solidity compiler solc location

### ISSUE THREAD

**Issue by ethers** [ethereum/pyethapp#54]
a config or command line option (geth has --solc) to specify the location of solc

**Comment by heikoheiko** [comment]
what's the use case here? why shouldn't solc be available in the path?

**Comment by ethers** [comment]
in dev, may have multiple versions of solc (eg especially since 0.1.2 had breaking changes, they may also  build 0.1.1).  also building solc from source, and having ppa, will lead to 2 potentially different solc, and it is sometimes helpful to use solc built from source.

**Comment by heikoheiko** [comment]
it's a bit hard to pass this down to the lib in pyethereum.
as a workaround you can either use an `alias` or a symlink in in your virtualenv `bin/` dir.

**Comment by ethers** [comment]
ok thanks for tip
