### ISSUE TITLE
coinbase but no accounts is confusing

### ISSUE THREAD

**Issue by ethers** [ethereum/pyethapp#55]
pyethapp/v1.0.1

It is confusing that there are no accounts, when a coinbase exists.  For consistency with other clients, the coinbase should be included as the first account.

```
In [46]: acct_service = eth.services.accounts

In [47]: acct_service.accounts
Out[47]: []

In [48]: eth.coinbase
Out[48]: '\xde\x0b)Vi\xa9\xfd\x93\xd5\xf2\x8d\x9e\xc8^@\xf4\xcbi{\xae'
```

**Comment by heikoheiko** [comment]
we use the default coinbase even if there is no account configured at all. this is mainly for automated zero config setups in which you don't want to have an account creation step. once you created an account this will also be the coinbase.

**Comment by ethers** [comment]
a note for others who may search, calling sendTransaction without any accounts gave the error "no sender account".  the particular confusion is that querying eth.coinbase gave the impression that there was already an account.  not obvious that an account has to be added when a user sees there's already a coinbase.

(maybe add the default coinbase to the docs, or an error message like "no accounts configured" is clearer)
