### ISSUE TITLE
eth.coinbase would be nicer in hex

### ISSUE THREAD

**Issue by ethers** [ethereum/pyethapp#56]
in pyethapp/v1.0.1 it is currently in bytes (user has to call `encode('hex')`)
```
In [48]: eth.coinbase
Out[48]: '\xde\x0b)Vi\xa9\xfd\x93\xd5\xf2\x8d\x9e\xc8^@\xf4\xcbi{\xae'
```

**Comment by heikoheiko** [comment]
yes, maybe we can wrap coinbase and addresses from accounts so that the __rep__ is hex encoded.
