### ISSUE TITLE
Account import unexpected keyword in call to add_account

### ISSUE THREAD

**Issue by holiman** [ethereum/pyethapp#57]
When trying to import a key:

	ubuntu@ubuntu-VirtualBox:~/tools/pyethapp$ pyethapp account import ../pyethereum/zkey.hex
	No handlers could be found for logger "eth.pow"
	INFO:app	using data in path=/home/ubuntu/.config/pyethapp
	INFO:config	loading config path=/home/ubuntu/.config/pyethapp
	CRITICAL:app	Move to EthApp.default_config 
	WARNING:accounts	keystore directory does not exist directory=/home/ubuntu/.config/pyethapp/keystore
	WARNING:accounts	no accounts found 
	INFO:app	registering service service=accounts
	Password to encrypt private key: 
	Repeat for confirmation: 
	Traceback (most recent call last):
	  File "/usr/local/bin/pyethapp", line 9, in <module>
	    load_entry_point('pyethapp==1.0.1', 'console_scripts', 'pyethapp')()
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
	    return self.main(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
	    rv = self.invoke(ctx)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
	    return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
	    return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
	    return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
	    return callback(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 16, in new_func
	    return f(get_current_context(), *args, **kwargs)
	  File "/home/ubuntu/tools/pyethapp/pyethapp/app.py", line 500, in import_account
	    app.services.accounts.add_account(account, path=account.address.encode('hex'))
	TypeError: add_account() got an unexpected keyword argument 'path'

I already have a PR from my account, so I'll just paste the fix here : 

	ubuntu@ubuntu-VirtualBox:~/tools/pyethapp$ git diff
	diff --git a/pyethapp/app.py b/pyethapp/app.py
	index 4542583..b8cbc1f 100644
	--- a/pyethapp/app.py
	+++ b/pyethapp/app.py
	@@ -496,8 +496,11 @@ def import_account(ctx, f, uuid):
	         password = click.prompt('Password to encrypt private key', default='', hide_input=True,
	                                 confirmation_prompt=True, show_default=False)
	     account = Account.new(password, privkey, uuid=id_)
	+    account.path = os.path.join(os.path.abspath(ctx.obj['config']['data_dir']),
	+                                ctx.obj['config']['accounts']['keystore_dir'],
	+                                account.address.encode('hex'))
	     try:
	-        app.services.accounts.add_account(account, path=account.address.encode('hex'))
	+        app.services.accounts.add_account(account)
	     except IOError:
	         click.echo('Could not write keystore file. Make sure you have write permission in the '
	                    'configured directory and check the log for further information.')

**Comment by jnnk** [comment]
Thank you!

Fixed in a7788d6cbe32d45f50b630ce001765e1d616ef9c (requires latest commit of pyethereum)
