### ISSUE TITLE
Allow network_id to be set by config.yaml

### ISSUE THREAD

**Issue by danielnovy** [ethereum/pyethapp#6]
In order to set network_id in current code one has to change his default value (0) in eth_protocol.py. May you please allow this important parameter to be set by config.yaml?

**Comment by heikoheiko** [comment]
added in: 7fba230eac4c04f5a42244cb33f783f973767701

useage: start with option `-c eth.network_id=X`

**Comment by heikoheiko** [comment]
to see how this is added to config.yaml, run:
`pyethapp config`
