### ISSUE TITLE
How to install required dependencies? (not a python user here)

### ISSUE THREAD

**Issue by stefek99** [ethereum/pyethapp#67]
Readme:

```
$ git clone https://github.com/ethereum/pyethapp
$ cd pyethapp
$ python setup.py install
```

Output:

```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

I tried:

```
sudo easy_install setuptools
pip install setuptools
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
```

I'm not a Python guy but decided to try Python client because:

> If you are interested in understanding how ethereum works and how to extend it, the code base of this client is probably the most readable and has a great contract tester library with fast development cycles.

Would be nice if I could run it without messing with dependencies.

Python 2.7.8 on Mac 10.10.5

**Comment by konradkonrad** [comment]
Hey @stefek99 
The error sounds odd, so here are a few suggestions that may or may not help:
1. I'd recommend to use a virtualenv (https://virtualenv.pypa.io/en/latest/), so you don't need to mess with your global dependencies. 
2. if the problem persists in the virtualenv, try using the suggested --upgrade flag (`pip install --upgrade setuptools`). Also try to (re-)install pip within the virtualenv (`pip install --upgrade pip`).
3. further debugging could involve opening a python repl (`python`) and try to `import setuptools` manually and see what it gives you..
   HTH!
