### ISSUE TITLE
Documentation: Installation, c_secp256k1

### ISSUE THREAD

**Issue by retotrinkler** [ethereum/pyethapp#69]
When using: `pyethapp run` I got the following warning:

`UserWarning: could not import c_secp256k1, fallback to bitcointools
  warnings.warn('could not import c_secp256k1, fallback to bitcointools')`

To fix it I had to install:
// Download c_secp256k1
git clone https://github.com/czepluch/pysecp256k1.git
cd pysecp256k1

// Dependencies for c_secp256k1
sudo apt-get install libssl-dev
sudo apt-get install libffi-dev
sudo apt-get install libtool

// Set-up c_secp256k1
sudo python setup.py install

**Comment by czepluch** [comment]
When did you last pull? At the moment c_secp256k1 shouldn't be a requirement.

**Comment by retotrinkler** [comment]
Today. It was just a warning I got. pyethapp run did execute

**Comment by czepluch** [comment]
Ah, yes of course. c_secp256k1 will soon be added back. Thank you.
