### ISSUE TITLE
Documentation: Installation, py-scrypt failed

### ISSUE THREAD

**Issue by retotrinkler** [ethereum/pyethapp#70]
Just further documenting the installation and invocation process I'm having

When using: `pyethapp run` I got the following warning:

`Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt`

To fix it I tried to install the following, BUT DID NOT SOLVE THE WARNING:

$ sudo apt-get install mercurial
$ hg clone http://bitbucket.org/mhallin/py-scrypt
$ cd py-scrypt
$ python setup.py build
Become superuser (or use virtualenv):
$ python setup.py install
Run tests after install:
$ python setup.py test

**Comment by enjoykin** [comment]
Got the same error. Please advice if there is any solution for that?

**Comment by AndrewBezold** [comment]
This may be old, but it's still open, and some may be still having trouble with it like I did at first, so:

Uninstall scrypt, if you have it installed

$ pip install scrypt

Then install or run the program as needed.

**Comment by retotrinkler** [comment]
thanks
