### ISSUE TITLE
Contract deployment, contract address not available

### ISSUE THREAD

**Issue by retotrinkler** [ethereum/pyethapp#76]
after: tx = eth.transact(to='', data = evm_code, startgas=3100000)

tx.creates returns NULL

instead of contract address

**Comment by asafazaria** [comment]
Had the same thing.

Looking through the code I think this might be a bug in the normalize_address function in console_service.py.

The function converts an empty to address " " to the null string "\x00\x00...".
For this reason the creates function returns None and no contracts are really deployed on the chain.

the bug would be in the statement:

a = a or '\0' \* 20 if allow_blank else a

if a is an empty string the first part will evaluate to (\0 *20) if allow_blank is True.
We need this the other way aroundL

a = a or '\0' \* 20 if (not allow_blank) else a

**Comment by heikoheiko** [comment]
fixed in 5b9c10fd04ed159b934812ccd6f39b36429ecc3a
