### ISSUE TITLE
Can not create contracts using the rpc_client

### ISSUE THREAD

**Issue by asafazaria** [ethereum/pyethapp#80]
There is an error sending transactions with an empty string as the "to" address.

the normalize_address function should be wrapped to allow empty strings the same way that was done in the console_service. Fixing this locally on my machine seems to solve the problem.

**Comment by heikoheiko** [comment]
this broke it:
https://github.com/ethereum/pyethapp/commit/6afb024c23f45abf4966c47ad8d6345620b60691
