### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by iPadGuy** [ethereum/pyethapp#82]
I cloned pyethapp to my Ubuntu 14.04 LTS installation, but following the README file instructions didn't quite work... 

**python setup.py install** failed because it didn't have write access to **/usr/local/lib/python2.7/dist-packages/test-easy-install-2597.write-test**. Using **sudo** built a binary that crashed.

**python setup.py install** also failed due to permission errors. Using **sudo** generated a bunch of warnings, but the binary seems to run.

**UPDATE:** Just for kicks, I retried **sudo python setup.py install** and it worked. Apparently, the **pip** installation installs some of the prerequisites.

**Comment by ulope** [comment]
Usually it's best never to install 3rd party libraries and tools into the global "System-Python".

Using a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) is almost always the better solution. 

We should probably mention this in the README / docs
