### ISSUE TITLE
[DEV] --fake flag doesn't set fake-difficulty anymore

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/pyethapp#93]

**Comment by heikoheiko** [comment]
@ms83 @ulope was this removed deliberately?

**Comment by ulope** [comment]
Not that I know. Looks like the code is still there: https://github.com/ethereum/pyethapp/blob/develop/pyethapp/app.py#L168

**Comment by konradkonrad** [comment]
Problem seems, that `eth.genesis` ~~still~~ even with `--fake` defaults to `genesis_frontier.json`

```
rm -rf /tmp/fake && pyethapp -d /tmp/fake -c pow.cpu_pct=90 run --fake --nodial
...
GENESIS_DIFFICULTY: 17179869184
genesis: /home/konrad/Projects/pyethapp/pyethapp/genesisdata/genesis_frontier.json
```

**Comment by panpilkarz** [comment]
This is the first time I see that code. No idea.

**Comment by ulope** [comment]
The code I linked probably needs to be updated to set the values in the config and not the defaults as it does now. This probably is a side effect of the changes done for the `--network` flag.
