### ISSUE TITLE
eth_syncing

### ISSUE THREAD

**Issue by jesuscript** [ethereum/pyethapp#96]
Could you please add this method to the RPC?

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing

**Comment by konradkonrad** [comment]
Hey @jesuscript -- I'm at it, please see 51bb9965c496e70838af5fd02b7202db5f07aed4 and https://github.com/ethereum/pyethapp/issues/44

**Comment by konradkonrad** [comment]
Resolved with https://github.com/ethereum/pyethapp/tree/v1.0.19

**Comment by jesuscript** [comment]
nice! thanks
